#!/usr/bin/env node
// PreToolUse(Read|Grep|Edit|Write|MultiEdit|NotebookEdit): keep agents away from secrets
// and from files that are generated by tools.
import {
  decide,
  isGeneratedPath,
  isSecretPath,
  readInput,
  toRepoPath,
} from './lib.mjs';

const input = readInput();
const filePath =
  input.tool_input?.file_path ??
  input.tool_input?.notebook_path ??
  input.tool_input?.path;

if (typeof filePath !== 'string' || filePath.length === 0) {
  process.exit(0);
}

const repoPath = toRepoPath(filePath);

if (repoPath.startsWith('..')) {
  process.exit(0);
}

if (isSecretPath(repoPath)) {
  decide(
    'deny',
    `${repoPath} holds secrets and is off-limits to agents. Use apps/core/.env.example for the variable names, and ask the user if you need a value.`
  );
}

const isWrite = !['Read', 'Grep'].includes(input.tool_name);

if (isWrite && repoPath.endsWith('.secret')) {
  decide(
    'deny',
    `${repoPath} is git-secret ciphertext. Only maintainers re-encrypt it with \`git secret hide\`.`
  );
}

if (isWrite && isGeneratedPath(repoPath)) {
  decide(
    'deny',
    `${repoPath} is generated. Change its source instead (component/auto-import config, package source, or pnpm commands for the lockfile).`
  );
}

process.exit(0);
